-- 코드를 입력하세요

WITH C AS (
    SELECT ORDER_ID,
    CASE WHEN OUT_DATE <= '2022-05-01' THEN '출고완료'
        WHEN OUT_DATE > '2022-05-01' THEN '출고대기'
        ELSE '출고미정' 
     END AS '출고여부'
    FROM FOOD_ORDER
)

SELECT F.ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, '%Y-%m-%d') AS OUT_DATE, C.출고여부
FROM FOOD_ORDER F
INNER JOIN C ON F.ORDER_ID = C.ORDER_ID
ORDER BY F.ORDER_ID ASC