-- 코드를 작성해주세요
SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO I
LEFT OUTER JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.ITEM_ID IS NULL
GROUP BY I.ITEM_ID, ITEM_NAME, RARITY
ORDER BY I.ITEM_ID DESC