-- 코드를 입력하세요


WITH C1 AS (
SELECT 1 FROM USER_INFO WHERE DATE_FORMAT(JOINED, '%Y') = 2021
)
, C2 AS (
SELECT COUNT(*) CNT
    FROM C1
)

, C3 AS (
SELECT DISTINCT O.USER_ID, SALES_DATE
FROM ONLINE_SALE O  
INNER JOIN USER_INFO U ON U.USER_ID = O.USER_ID
WHERE DATE_FORMAT(JOINED, '%Y') = 2021
# GROUP BY DATE_FORMAT(SALES_DATE, '%Y-%m')
)

SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT(USER_ID)) PURCHASED_USERS, ROUND(COUNT(DISTINCT(USER_ID))/ CNT, 1) PURCHASED_RATIO
FROM C3
JOIN C2 
GROUP BY DATE_FORMAT(SALES_DATE, '%Y-%m')
ORDER BY YEAR ASC, MONTH ASC

