WITH J_CNT AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE DATE_FORMAT(JOINED, "%Y") = 2021
),

    NUM AS (
        SELECT DISTINCT COUNT(*) C
        FROM J_CNT 
    )

    SELECT DATE_FORMAT(SALES_DATE, '%Y') YEAR,
    DATE_FORMAT(SALES_DATE, '%m') MONTH,
    COUNT(DISTINCT OS.USER_ID) PURCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / NUM.C, 1) PUCHASED_RATIO
    FROM ONLINE_SALE OS
    INNER JOIN J_CNT ON OS.USER_ID = J_CNT.USER_ID
    JOIN NUM
    GROUP BY DATE_FORMAT(SALES_DATE, '%Y-%m')
    ORDER BY DATE_FORMAT(SALES_DATE, '%Y-%m')

