-- 코드를 입력하세요
SELECT P.PRODUCT_ID, PRODUCT_NAME, PRICE*SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER O 
INNER JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE O.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY P.PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC