-- 코드를 입력하세요
WITH
truck_his AS (
SELECT H.HISTORY_ID, C.CAR_TYPE, C.DAILY_FEE, TIMESTAMPDIFF(DAY,START_DATE, END_DATE) +1 AS DAY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE LIKE '트럭'
)
,
plan AS (
SELECT DISCOUNT_RATE,
    CASE DURATION_TYPE
    WHEN '7일 이상' THEN 7
    WHEN '30일 이상' THEN 30
    WHEN '90일 이상' THEN 90
    END AS min_date,

CASE DURATION_TYPE
    WHEN '7일 이상' THEN 30
    WHEN '30일 이상' THEN 90
    WHEN '90일 이상' THEN 99999999
    END AS max_date
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
WHERE CAR_TYPE LIKE '트럭'
)

SELECT T.HISTORY_ID, ROUND(T.DAILY_FEE * T.DAY * (100- IFNULL(P.DISCOUNT_RATE, 0 ))/ 100, 0) AS FEE
FROM truck_his T
LEFT JOIN plan P ON
T.DAY >= P.min_date AND
T.DAY < P.max_date
ORDER BY FEE DESC, HISTORY_ID DESC



# 트럭의 대여기록 , 대여금액, 