-- 코드를 입력하세요
WITH C1 AS (
SELECT HISTORY_ID, TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 AS DIFF_DAY,(TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 )  * DAILY_FEE AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
INNER JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE LIKE '트럭'
)

, C2 AS (
SELECT CAST(SUBSTRING_INDEX (DURATION_TYPE, '일', 1) AS UNSIGNED) DURATION, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE LIKE '트럭'
)

, C3 AS (
SELECT 
HISTORY_ID, MAX(DISCOUNT_RATE) AS DISCOUNT_RATE
FROM C1
INNER JOIN C2 ON DIFF_DAY >= DURATION
GROUP BY HISTORY_ID
# ORDER BY HISTORY_ID
)

SELECT C1.HISTORY_ID, CAST ((100 - IFNULL(DISCOUNT_RATE, 0)) /100 * FEE AS UNSIGNED )AS FEE
FROM C1 
LEFT OUTER JOIN C3 ON C1.HISTORY_ID = C3.HISTORY_ID
ORDER BY FEE DESC, C1.HISTORY_ID DESC

