-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD 
# SELECT *
FROM APPOINTMENT A
JOIN PATIENT P ON 
A.PT_NO = P.PT_NO
JOIN DOCTOR D ON
D.DR_ID = A.MDDR_ID
WHERE APNT_CNCL_YN = 'N'
# DATE_FORMAT( IFNULL(APNT_CNCL_YMD, '2022-04-01'), 'YY-mm-dd') != '2022-04-13'
AND A.MCDP_CD LIKE 'CS'
AND DATE(A.APNT_YMD) = '2022-04-13'
ORDER BY APNT_YMD ASC