-- 코드를 입력하세요
WITH RECURSIVE E1 AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1 
    FROM E1
    WHERE HOUR < 23
    
)

,
E2 AS (
    SELECT COUNT(ANIMAL_ID) COUNT, DATE_FORMAT(DATETIME, "%H") AS HOUR
    FROM ANIMAL_OUTS
    GROUP BY DATE_FORMAT(DATETIME, "%H")
)

SELECT E1.HOUR HOUR, IFNULL(E2.COUNT, 0) COUNT
FROM E1 
LEFT OUTER JOIN E2 ON E1.HOUR = E2.HOUR
ORDER BY HOUR ASC

  
