WITH FE AS (
    SELECT SUM(CODE) C
    FROM SKILLCODES 
    WHERE CATEGORY LIKE 'FRONT END'
) 

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D, FE
WHERE (D.SKILL_CODE & FE.C) > 0
ORDER BY ID