-- 코드를 입력하세요
SELECT M.MEMBER_NAME, R2.REVIEW_TEXT, TO_CHAR ( R2.REVIEW_DATE, 'YYYY-MM-DD' ) AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R2 ON M.MEMBER_ID = R2.MEMBER_ID
JOIN 
    (
        SELECT *
        FROM (
        SELECT MEMBER_ID, COUNT(*) AS CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID 
        -- HAVING MAX(CNT)
        ORDER BY CNT DESC
        )
        WHERE ROWNUM <= 1
    ) R1
ON M.MEMBER_ID = R1.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
