-- 코드를 입력하세요
SELECT DATE_FORMAT(C1.START_DATE, '%m') AS MONTH, C1.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C1
WHERE C1.START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
AND CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
GROUP BY C1.CAR_ID, DATE_FORMAT(C1.START_DATE, '%Y-%m')
HAVING RECORDS IS NOT NULL
ORDER BY DATE_FORMAT(C1.START_DATE, '%m') ASC, C1.CAR_ID DESC
