-- 코드를 입력하세요
# SELECT B.CATEGORY, 
# FROM BOOK_SALES AS BS 
# JOIN BOOK AS B ON BS.BOOK_ID = B.BOOK_ID
# ORDER BY CATEGORY ASC



SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES AS BS 
JOIN BOOK AS B ON BS.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY CATEGORY ASC
